### ISSUE TITLE
测试ant debug成功后，使用ant auto-release打包不成功，提示Cannot run program "ant" (in directory "D:\dev\github\AntDemo-masterTmp")

### ISSUE THREAD

**Issue by jacky0karl** [sinkcup/AntDemo#17]

**Comment by shaunthegeek** [comment]
Android是Linux，建议使用Linux桌面进行开发。由于没有Windows开发环境，所以无法解答你的问题。
参考 http://www.cnblogs.com/sink_cup/p/android-ant-auto-release.html#2954620
